### ISSUE TITLE
guile for make

### ISSUE THREAD

**Issue by pavelvasev** [gnu-mcu-eclipse/build-scripts#9]
Could you please enable [guile feature for make](https://www.gnu.org/software/make/manual/html_node/Guile-Integration.html)?
We use guile in makefile in our project under linux,
and now we are facing the problem of porting compilation process to windows...

If it is impossible, we would appreciate any advice!..

Thank you!

**Comment by ilg-ul** [comment]
Please add this issue to the windows build tools, this project is deprecated.
